-- Criar tabela de protocolo_digital
CREATE TABLE IF NOT EXISTS protocolo_digital (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_protocolo VARCHAR(50) NOT NULL UNIQUE,
  requerente_nome VARCHAR(255) NOT NULL,
  requerente_matricula VARCHAR(50),
  secretaria VARCHAR(100) NOT NULL,
  tipo_solicitacao VARCHAR(100) NOT NULL,
  descricao TEXT,
  status VARCHAR(30) NOT NULL DEFAULT 'Aberto' CHECK (status IN ('Aberto', 'Em Análise', 'Concluído')),
  prioridade VARCHAR(30) DEFAULT 'Normal',
  responsavel VARCHAR(255),
  data_conclusao DATE,
  data_abertura TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  prazo_estimado DATE,
  historico_tramitacao JSONB DEFAULT '[]'::jsonb,
  documento_anexo VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Criar índices para melhor performance
CREATE INDEX IF NOT EXISTS idx_protocolo_status ON protocolo_digital(status);
CREATE INDEX IF NOT EXISTS idx_protocolo_secretaria ON protocolo_digital(secretaria);
CREATE INDEX IF NOT EXISTS idx_protocolo_requerente ON protocolo_digital(requerente_nome);
CREATE INDEX IF NOT EXISTS idx_protocolo_data ON protocolo_digital(data_abertura);


-- Atualizar check constraint de status, coluna de prioridade, responsável e data de conclusão se a tabela já existir no Supabase
ALTER TABLE IF EXISTS protocolo_digital DROP CONSTRAINT IF EXISTS protocolo_digital_status_check;
ALTER TABLE IF EXISTS protocolo_digital ADD CONSTRAINT protocolo_digital_status_check CHECK (status IN ('Aberto', 'Em Análise', 'Concluído'));
ALTER TABLE IF EXISTS protocolo_digital ADD COLUMN IF NOT EXISTS prioridade VARCHAR(30) DEFAULT 'Normal';
ALTER TABLE IF EXISTS protocolo_digital ADD COLUMN IF NOT EXISTS responsavel VARCHAR(255);
ALTER TABLE IF EXISTS protocolo_digital ADD COLUMN IF NOT EXISTS data_conclusao DATE;

-- Desabilitar RLS para permitir inserções/consultas públicas via API
ALTER TABLE protocolo_digital DISABLE ROW LEVEL SECURITY;
