-- Criar tabela de equipamentos
CREATE TABLE equipamentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  tipo VARCHAR(100) NOT NULL,
  localizacao VARCHAR(255) NOT NULL,
  status VARCHAR(20) NOT NULL CHECK (status IN ('active', 'maintenance', 'inactive')),
  data_instalacao DATE NOT NULL,
  data_ultima_manutencao DATE,
  modelo VARCHAR(100),
  numero_serie VARCHAR(100) UNIQUE,
  descricao TEXT,
  secretaria VARCHAR(100),
  responsavel VARCHAR(100),
  fabricante VARCHAR(50) NOT NULL DEFAULT 'Outros',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Criar índices para melhor performance
CREATE INDEX idx_equipamentos_status ON equipamentos(status);
CREATE INDEX idx_equipamentos_tipo ON equipamentos(tipo);
CREATE INDEX idx_equipamentos_localizacao ON equipamentos(localizacao);
CREATE INDEX idx_equipamentos_secretaria ON equipamentos(secretaria);
CREATE INDEX idx_equipamentos_fabricante ON equipamentos(fabricante);

-- Criar trigger para atualizar o campo updated_at automaticamente
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_equipamentos_updated_at 
    BEFORE UPDATE ON equipamentos 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Inserir dados de exemplo (opcional)
INSERT INTO equipamentos (
  nome, tipo, localizacao, status, data_instalacao, data_ultima_manutencao, 
  modelo, numero_serie, secretaria, responsavel, fabricante
) VALUES 
  (
    'Catraca Biométrica A1', 
    'Catraca', 
    'Secretaria de Educação - Sede', 
    'active', 
    '2023-01-15', 
    '2024-03-01',
    'BioGate Pro',
    'BGP2023001',
    'Educação',
    'João Silva',
    'Control ID'
  ),
  (
    'Leitor Facial B2', 
    'Leitor Facial', 
    'Secretaria de Saúde - Posto Central', 
    'active', 
    '2023-02-20', 
    '2024-02-15',
    'FaceID 2000',
    'FID2023002',
    'Saúde',
    'Maria Santos',
    'Control ID'
  ),
  (
    'Catraca Biométrica C3', 
    'Catraca', 
    'Secretaria de Educação - Escola Municipal 1', 
    'maintenance', 
    '2023-03-10', 
    '2024-01-20',
    'BioGate Pro',
    'BGP2023003',
    'Educação',
    'Pedro Costa',
    'Control ID'
  ),
  (
    'Leitor Digital D4', 
    'Leitor Digital', 
    'Secretaria de Administração', 
    'active', 
    '2023-04-05', 
    '2024-03-10',
    'DigitalScan X',
    'DSX2023004',
    'Administração',
    'Ana Oliveira',
    'Control ID'
  ),
  (
    'Catraca Biométrica E5', 
    'Catraca', 
    'Secretária de Saúde - Posto Norte', 
    'inactive', 
    '2023-05-12', 
    '2023-12-01',
    'BioGate Pro',
    'BGP2023005',
    'Saúde',
    'Carlos Ferreira',
    'Control ID'
  ),
  (
    'Leitor Facial F6', 
    'Leitor Facial', 
    'Secretaria de Educação - Escola Municipal 2', 
    'active', 
    '2023-06-18', 
    '2024-02-28',
    'FaceID 2000',
    'FID2023006',
    'Educação',
    'Lucia Pereira',
    'Control ID'
  ),
  (
    'Catraca Tommi T11', 
    'Catraca', 
    'Secretaria de Educação - Escola Municipal 3', 
    'active', 
    '2023-07-10', 
    '2024-03-05',
    'Tommi Pro',
    'TMP2023011',
    'Educação',
    'Marcos Silva',
    'Tommi'
  ),
  (
    'Leitor Tommi T12', 
    'Leitor Digital', 
    'Secretaria de Saúde - Posto Sul', 
    'active', 
    '2023-08-15', 
    '2024-02-20',
    'Tommi Scan',
    'TMS2023012',
    'Saúde',
    'Juliana Santos',
    'Tommi'
  );

-- Habilitar RLS (Row Level Security) para maior segurança
ALTER TABLE equipamentos ENABLE ROW LEVEL SECURITY;

-- Criar política para permitir leitura pública (se necessário)
CREATE POLICY "Equipamentos são visíveis para todos" ON equipamentos
  FOR SELECT USING (true);

-- Criar política para permitir inserções autenticadas
CREATE POLICY "Equipamentos podem ser inseridos por usuários autenticados" ON equipamentos
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Criar política para permitir atualizações autenticadas
CREATE POLICY "Equipamentos podem ser atualizados por usuários autenticados" ON equipamentos
  FOR UPDATE USING (auth.role() = 'authenticated');

-- Criar política para permitir deleções autenticadas
CREATE POLICY "Equipamentos podem ser deletados por usuários autenticados" ON equipamentos
  FOR DELETE USING (auth.role() = 'authenticated');
